blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('', BlogListView.as_view(), name='blog_list'),
    path('<int:pk>/view', BlogDetailView.as_view(), name='blog_view'),
    path('<int:pk>/update', BlogUpdateView.as_view(), name='blog_edit'),
    path('<int:pk>/delete', BlogDeleteView.as_view(), name='blog_delete'),
]

djangoProject1/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include('blog.urls', namespace='blog')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.CharField(max_length=255, unique=True, db_index=True, null=True, blank=True, verbose_name="url")
    body = models.TextField(max_length=250, verbose_name='Cодержимое', blank=True, null=True)
    image = models.ImageField(upload_to='blog/photo', verbose_name='Изображение', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания(записи в БД)')
    is_published = models.BooleanField(default=True, verbose_name='Признак публикации')
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

blog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify
from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'body', 'image')
    template_name = 'blog/blog_form.html'
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog
    template_name = 'blog/blog_list.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blog/blog_detail.html'
    success_url = reverse_lazy('blog:blog_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'body', 'image')
    template_name = 'blog/blog_form.html'
    success_url = reverse_lazy('blog:blog_list')

    def get_success_url(self):
        return reverse('blog:blog_view', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    template_name = 'blog/blog_confirm_delete.html'
    success_url = reverse_lazy('blog:blog_list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}


<div class="col-lg-12">
    <div class="card-body card-center">
        <form method="post" action="" class="form-floating text-center">
            {% csrf_token %}
            <h1>Хотите удалить статью "{{blog.title}}"?</h1>
            <button type="submit" class="btn btn-lg btn-success">Подтвердить</button>
            <a href="{%url 'blog:blog_list'%}" role="button" class="btn btn-lg btn-danger">Отменить</a>
        </form>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Блоги</h1>
</div>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% if blog.is_published %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h2 class="card-text text-center">{{ blog.title }} ({{ blog.slug }})</h2>
                        <img src="{{ blog.image | media_filter }}" class="img-fluid mb-4">
                        <p class="card-text">Содержимое: {{ blog.body }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
                                <a href="{% url 'blog:blog_edit' blog.pk %}" type="button"
                                   class="btn btn-sm btn-secondary">Изменить</a>
                                <a href="{% url 'blog:blog_delete' blog.pk %}" type="button"
                                   class="btn btn-sm btn-danger">Удалить</a>
                            </div>
                        </div>
                        <div class="card card-body m-3">
                            <p class="my-0 font-weight-normal text-center">Просмотры: {{ blog.views_count }}</p>
                        </div>
                        <a href="{% url 'blog:blog_list' %}" style="float: right" type="button"
                           class="btn btn-lg btn-info">Назад</a>
                        <figcaption style="float: down" class="blockquote-footer mt-4">
                            Создано: {{ blog.created_at }}
                        </figcaption>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-lg-3 col-md-6 col-sm-12 m-3">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data" action="" class="form-floating">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="d-grid gap-2 col-10 mx-auto">
                    {% if object %}
                    <button type="submit" class="btn btn-lg btn-block btn-success">Изменить</button>
                    <a href="{% url 'blog:blog_list' %}" type="submit" class="btn btn-lg btn-block btn-danger mt-1">Отмена</a>
                    {% else %}
                    <button type="submit" class="btn btn-lg btn-block btn-success">Создать</button>
                    <a href="{% url 'blog:blog_list' %}" type="submit" class="btn btn-lg btn-block btn-danger mt-1">Назад</a>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Заметки наших покупателей и гостей</h1>
</div>
<div class="album py-5 bg-body-tertiary">
    <div class="d-grid gap-2 col-2 mx-auto mb-4">
        <a href="{% url 'blog:blog_create' %}" type="button" class="btn btn-lg btn-block btn-primary">Создать запись</a>
    </div>
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for blog in blog_list %}
            {% if blog.is_published %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h4 class="card-text text-center">{{ blog.title }}</h4>
                        <img class="card-img-top mb-4" src="{{ blog.image | media_filter }}">
                        <p class="card-text">{{ blog.body | truncatechars:100 }}</p>
                        <div class="d-grid gap-2  mx-auto">
                            <a href="{% url 'blog:blog_view' blog.pk %}" class="btn btn-sm btn-primary">Посмотреть</a>
                            <a href="{% url 'blog:blog_edit' blog.pk %}" class="btn btn-sm btn-secondary">Изменить</a>
                        </div>
                        <a href="{% url 'blog:blog_delete' blog.pk %}" type="button"
                           class="btn btn-md mt-3 btn-danger" style="float:right">Удалить</a>
                        <p class="text-body-secondary text-sm"></p>
                        <figcaption class="blockquote-footer mt-4">
                            Создано: {{ blog.created_at }}
                        </figcaption>
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}